### ISSUE TITLE
Rtools42

### ISSUE THREAD

**Issue by yutannihilation** [facorread/rtools-chocolatey#4]
Disclaimer: I don't have strong opinion here. I understand the statement "Rtools40 works well with R 4.2 so it's enough" and still hope R will come back to Rtools40, but some people really need Rtools42 to test their R projects and I'm one of those; since [GitHub Actions rely on this repository to install Rtools](https://github.com/actions/virtual-environments/blob/184da3fa5c67ee72fa457024c6f0cea6e5a27b74/images/win/scripts/Installers/Install-R.ps1#L7), Rtools42 will never come to GitHub Actions runner unless this repository adopts Rtools42.

**Comment by jeroen** [comment]
It is updated to rtools43 now.

**Comment by yutannihilation** [comment]
Great! Thank you so much.
